-- Inserindo CATEGORIAS
INSERT INTO TB_CATEGORIA (DESCRICAO, VALOR_HORA) VALUES ('JUNIOR', 1500.00);
INSERT INTO TB_CATEGORIA (DESCRICAO, VALOR_HORA) VALUES ('PLENO', 2500.00);
INSERT INTO TB_CATEGORIA (DESCRICAO, VALOR_HORA) VALUES ('SENIOR', 4500.00);

-- Inserindo ADVOGADOS
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('MACK', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '1');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('DANNY', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170','1');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('DEBORAH', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '2');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('LAURA', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '1');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('SAMARA', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '3');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('JUNIM', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '2');
INSERT INTO TB_ADVOGADO (NOME, CPF, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, CATEGORIA_ID) VALUES ('LEILA', '00000000000', 'RUA DESEMBARGADOR CONTINENTINO, 120', 'CASA', 'CAICARA', 'BH', 'MG','30720170', '3');



-- Inserindo CONTRATO

INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (0);
INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (1, 300);
INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (1, 250);
INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (0);
INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (2, 1000, 10);
INSERT INTO TB_CONTRATO (TIPO_HORA, VALOR, DESCONTO) VALUES (0, ,10);


-- Inserindo CLIENTES
INSERT INTO TB_CLIENTE (NOME, CNPJ_CPF, CONTATO, TELEFONE, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, OBS) VALUES ('M3TECH', '0000000000000','MACK','999999999','RUA DE CASA, 150',' ','CAICARA','BH','MG','35050100','CLIENTE BOM');
INSERT INTO TB_CLIENTE (NOME, CNPJ_CPF, CONTATO, TELEFONE, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, OBS) VALUES ('M3INFO', '0000000000000','DEBORAH','999999999','RUA DE CASA, 150',' ','CAICARA','BH','MG','35050100','CLIENTE BOM');
INSERT INTO TB_CLIENTE (NOME, CNPJ_CPF, CONTATO, TELEFONE, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, OBS) VALUES ('SOFTHOUSE', '0000000000000','LAURA','999999999','RUA DE CASA, 150',' ','CAICARA','BH','MG','35050100','CLIENTE BOM');
INSERT INTO TB_CLIENTE (NOME, CNPJ_CPF, CONTATO, TELEFONE, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, OBS) VALUES ('CAOS', '0000000000000','JUNIM','999999999','RUA DE CASA, 150',' ','CAICARA','BH','MG','35050100','CLIENTE BOM'); 
INSERT INTO TB_CLIENTE (NOME, CNPJ_CPF, CONTATO, TELEFONE, ENDERECO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, OBS) VALUES ('JACQUES ADV', '0000000000000','DEBORAH','999999999','RUA DE CASA, 150',' ','CAICARA','BH','MG','35050100','CLIENTE BOM');



-- Inserindo CASO
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 1', 1, 1);
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 2', 1, 2);
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 3', 2, 3);
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 4', 3, 4);
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 5', 2, 5);
INSERT INTO TB_CASO (DESCRICAO, CLIENTE_ID, CONTRATO_ID) VALUES ('EXEMPLO 6', 3, 6);



-- Inserindo TIMESHEET
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-10-10', '1:00:00', 'Atendimento', 1, 1, 1);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-11-12', '1:40:00', 'Atendimento', 2, 1, 2);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-09-20', '0:30:00', 'Atendimento', 2, 1, 1);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-10-21', '5:30:00', 'Atendimento', 3, 2, 3);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-09-13', '2:10:00', 'Atendimento', 2, 3, 4);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-11-15', '2:40:00', 'Atendimento', 2, 3, 6);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-10-16', '3:10:00', 'Atendimento', 3, 2, 5);
INSERT INTO TB_TIMESHEET (DATA, TEMPO, DESCRICAO, ADVOGADO_ID, CLIENTE_ID, CASO_ID) VALUES ('2020-09-18', '1:10:00', 'Atendimento', 4, 3, 4);


